create extension if not exists pgcrypto;

create table if not exists public.sql_case_questions (
  id bigint generated by default as identity primary key,
  phase smallint not null check (phase between 1 and 3),
  order_num smallint not null,
  prompt text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  correct_index smallint not null check (correct_index between 0 and 3),
  unique (phase, order_num)
);

create table if not exists public.sql_case_runs (
  id uuid primary key default gen_random_uuid(),
  class text not null,
  title text not null default 'SQL Audit Investigation',
  status text not null default 'hidden' check (status in (
    'hidden', 'checkin',
    'phase1_active', 'phase1_results',
    'phase2_active', 'phase2_results',
    'phase3_active', 'phase3_results',
    'groups_ready', 'audit_active', 'finished'
  )),
  checkin_code_hash text not null,
  phase_duration_seconds integer not null default 300 check (phase_duration_seconds = 300),
  stage_started_at timestamptz,
  stage_deadline timestamptz,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sql_case_runs_class_created_idx
  on public.sql_case_runs (class, created_at desc);

create table if not exists public.sql_case_participants (
  run_id uuid not null references public.sql_case_runs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  checked_in_at timestamptz not null default now(),
  primary key (run_id, user_id)
);

create table if not exists public.sql_case_answers (
  run_id uuid not null references public.sql_case_runs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  phase smallint not null check (phase between 1 and 3),
  question_id bigint not null references public.sql_case_questions(id) on delete cascade,
  answer_index smallint not null check (answer_index between 0 and 3),
  answered_at timestamptz not null default now(),
  primary key (run_id, user_id, question_id)
);

create index if not exists sql_case_answers_progress_idx
  on public.sql_case_answers (run_id, phase, user_id);

create table if not exists public.sql_case_phase_submissions (
  run_id uuid not null references public.sql_case_runs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  phase smallint not null check (phase between 1 and 3),
  submitted_at timestamptz not null default now(),
  auto_submitted boolean not null default false,
  elapsed_seconds integer not null,
  correct_count integer not null,
  question_count integer not null,
  accuracy_score numeric(7,3) not null,
  speed_score numeric(7,3) not null,
  total_score numeric(7,3) not null,
  primary key (run_id, user_id, phase)
);

create table if not exists public.sql_case_groups (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.sql_case_runs(id) on delete cascade,
  group_number integer not null,
  total_qualification_score numeric(9,3) not null default 0,
  created_at timestamptz not null default now(),
  unique (run_id, group_number)
);

create table if not exists public.sql_case_group_members (
  group_id uuid not null references public.sql_case_groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  qualification_score numeric(7,3) not null,
  primary key (group_id, user_id),
  unique (user_id, group_id)
);

create index if not exists sql_case_group_members_user_idx
  on public.sql_case_group_members (user_id);

create table if not exists public.sql_case_audit_procedures (
  id bigint generated by default as identity primary key,
  order_num smallint not null unique,
  title text not null,
  instruction text not null,
  expected_columns text[] not null default '{}'
);

create table if not exists public.sql_case_worksheets (
  group_id uuid not null references public.sql_case_groups(id) on delete cascade,
  procedure_id bigint not null references public.sql_case_audit_procedures(id) on delete cascade,
  query_text text not null default '',
  conclusion text not null default '',
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  primary key (group_id, procedure_id)
);

alter table public.sql_case_questions enable row level security;
alter table public.sql_case_runs enable row level security;
alter table public.sql_case_participants enable row level security;
alter table public.sql_case_answers enable row level security;
alter table public.sql_case_phase_submissions enable row level security;
alter table public.sql_case_groups enable row level security;
alter table public.sql_case_group_members enable row level security;
alter table public.sql_case_audit_procedures enable row level security;
alter table public.sql_case_worksheets enable row level security;

revoke all on public.sql_case_questions from anon, authenticated;
revoke all on public.sql_case_runs from anon, authenticated;
revoke all on public.sql_case_participants from anon, authenticated;
revoke all on public.sql_case_answers from anon, authenticated;
revoke all on public.sql_case_phase_submissions from anon, authenticated;
revoke all on public.sql_case_groups from anon, authenticated;
revoke all on public.sql_case_group_members from anon, authenticated;
revoke all on public.sql_case_audit_procedures from anon, authenticated;
revoke all on public.sql_case_worksheets from anon, authenticated;

grant all on public.sql_case_questions to service_role;
grant all on public.sql_case_runs to service_role;
grant all on public.sql_case_participants to service_role;
grant all on public.sql_case_answers to service_role;
grant all on public.sql_case_phase_submissions to service_role;
grant all on public.sql_case_groups to service_role;
grant all on public.sql_case_group_members to service_role;
grant all on public.sql_case_audit_procedures to service_role;
grant all on public.sql_case_worksheets to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.sql_case_questions (phase, order_num, prompt, options, correct_index) values
(1, 1, 'Query mana yang menampilkan seluruh pengguna dengan akun aktif?',
 '["SELECT * FROM users WHERE account_status = ''ACTIVE'';","SELECT * FROM users HAVING account_status = ''ACTIVE'';","SELECT ACTIVE FROM users;","SELECT * WHERE account_status = ''ACTIVE'' FROM users;"]', 0),
(1, 2, 'Tampilkan username dan full_name pengguna Finance, urut berdasarkan full_name.',
 '["SELECT username, full_name FROM users WHERE department = ''Finance'' ORDER BY full_name;","SELECT username, full_name WHERE department = ''Finance'' FROM users ORDER full_name;","SELECT * FROM users ORDER BY department = ''Finance'';","SELECT username, full_name FROM users GROUP BY full_name WHERE department = ''Finance'';"]', 0),
(1, 3, 'Query mana yang mencari seluruh login gagal dari kode negara SG?',
 '["SELECT * FROM login_logs WHERE login_status = ''FAILED'' AND country_code = ''SG'';","SELECT * FROM login_logs WHERE login_status = ''FAILED'' OR country_code = ''SG'';","SELECT * FROM login_logs WHERE login_status IN (''FAILED'' AND ''SG'');","SELECT FAILED, SG FROM login_logs;"]', 0),
(1, 4, 'Cari login pada 20 Agustus 2026 antara pukul 22:00 dan 23:00.',
 '["SELECT * FROM login_logs WHERE attempted_at BETWEEN ''2026-08-20 22:00:00'' AND ''2026-08-20 23:00:00'';","SELECT * FROM login_logs WHERE attempted_at = ''2026-08-20 22:00:00'' AND ''2026-08-20 23:00:00'';","SELECT * FROM login_logs BETWEEN attempted_at ''2026-08-20 22:00:00'' AND ''2026-08-20 23:00:00'';","SELECT * FROM login_logs WHERE attempted_at > ''2026-08-20 22:00:00'' OR attempted_at < ''2026-08-20 23:00:00'';"]', 0),
(1, 5, 'Tampilkan aktivitas database yang menargetkan finance_payments atau employee_payroll.',
 '["SELECT * FROM database_activity WHERE target_table IN (''finance_payments'', ''employee_payroll'');","SELECT * FROM database_activity WHERE target_table = ''finance_payments'' AND ''employee_payroll'';","SELECT * FROM database_activity WHERE target_table LIKE (''finance_payments'', ''employee_payroll'');","SELECT target_table FROM database_activity WHERE IN = ''finance_payments'', ''employee_payroll'';"]', 0),
(1, 6, 'Query mana yang hanya menampilkan aktivitas database yang melakukan ekspor?',
 '["SELECT * FROM database_activity WHERE exported = 1;","SELECT * FROM database_activity WHERE exported IS NULL;","SELECT exported = 1 FROM database_activity;","SELECT * FROM database_activity HAVING query_type = ''exported'';"]', 0),
(1, 7, 'Cari aset workstation dengan hostname yang diawali WKS-.',
 '["SELECT * FROM assets WHERE hostname LIKE ''WKS-%'';","SELECT * FROM assets WHERE hostname = ''WKS-%'';","SELECT * FROM assets WHERE hostname LIKE ''%WKS-'';","SELECT * FROM assets WHERE hostname IN ''WKS-%'';"]', 0),
(1, 8, 'Cari traffic lebih dari 10.000.000 byte menuju alamat eksternal yang tidak diawali 10..',
 '["SELECT * FROM network_traffic WHERE bytes_sent > 10000000 AND destination_ip NOT LIKE ''10.%'';","SELECT * FROM network_traffic WHERE bytes_sent > 10000000 OR destination_ip NOT LIKE ''10.%'';","SELECT * FROM network_traffic WHERE bytes_sent < 10000000 AND destination_ip LIKE ''10.%'';","SELECT * FROM network_traffic HAVING bytes_sent > 10000000, destination_ip NOT ''10.%'';"]', 0),
(1, 9, 'Query mana yang menemukan login tanpa aset terdaftar?',
 '["SELECT * FROM login_logs WHERE asset_id IS NULL;","SELECT * FROM login_logs WHERE asset_id = NULL;","SELECT * FROM login_logs WHERE asset_id IS EMPTY;","SELECT NULL FROM login_logs WHERE asset_id;"]', 0),
(1, 10, 'Tampilkan laporan berstatus OPEN dengan severity HIGH atau MEDIUM.',
 '["SELECT * FROM incident_reports WHERE report_status = ''OPEN'' AND severity IN (''HIGH'', ''MEDIUM'');","SELECT * FROM incident_reports WHERE report_status = ''OPEN'' OR severity IN (''HIGH'', ''MEDIUM'');","SELECT * FROM incident_reports WHERE report_status AND severity = ''OPEN'', ''HIGH'', ''MEDIUM'';","SELECT * FROM incident_reports WHERE report_status = ''OPEN'' AND severity = ''HIGH'' AND severity = ''MEDIUM'';"]', 0),
(2, 1, 'Hitung jumlah login untuk setiap status.',
 '["SELECT login_status, COUNT(*) AS total FROM login_logs GROUP BY login_status;","SELECT login_status, COUNT(*) AS total FROM login_logs ORDER BY login_status;","SELECT COUNT(login_status) FROM login_logs WHERE login_status;","SELECT login_status, SUM(login_status) FROM login_logs;"]', 0),
(2, 2, 'Hitung rata-rata bytes_sent untuk setiap tanggal.',
 '["SELECT DATE(captured_at) AS activity_date, AVG(bytes_sent) AS avg_bytes FROM network_traffic GROUP BY DATE(captured_at);","SELECT DATE(captured_at), AVG(bytes_sent) FROM network_traffic GROUP BY bytes_sent;","SELECT captured_at, AVG(bytes_sent) FROM network_traffic;","SELECT AVG(DATE(captured_at)), bytes_sent FROM network_traffic GROUP BY captured_at;"]', 0),
(2, 3, 'Hitung jumlah network event untuk setiap jam.',
 '["SELECT HOUR(captured_at) AS activity_hour, COUNT(*) AS total FROM network_traffic GROUP BY HOUR(captured_at);","SELECT HOUR(captured_at), COUNT(*) FROM network_traffic GROUP BY captured_at;","SELECT captured_at, COUNT(HOUR(*)) FROM network_traffic;","SELECT HOUR, COUNT(*) FROM network_traffic ORDER BY captured_at;"]', 0),
(2, 4, 'Hitung total returned_rows untuk setiap user_id pada aktivitas ekspor.',
 '["SELECT user_id, SUM(returned_rows) AS total_rows FROM database_activity WHERE exported = 1 GROUP BY user_id;","SELECT user_id, SUM(returned_rows) FROM database_activity GROUP BY exported = 1;","SELECT SUM(user_id), returned_rows FROM database_activity WHERE exported = 1;","SELECT user_id, COUNT(returned_rows) FROM database_activity WHERE exported = 1;"]', 0),
(2, 5, 'Cari tanggal yang memiliki lebih dari 20 login gagal.',
 '["SELECT DATE(attempted_at), COUNT(*) AS failures FROM login_logs WHERE login_status = ''FAILED'' GROUP BY DATE(attempted_at) HAVING COUNT(*) > 20;","SELECT DATE(attempted_at), COUNT(*) FROM login_logs HAVING login_status = ''FAILED'' AND COUNT(*) > 20;","SELECT DATE(attempted_at), COUNT(*) FROM login_logs WHERE COUNT(*) > 20 GROUP BY login_status;","SELECT attempted_at FROM login_logs WHERE login_status = ''FAILED'' AND COUNT(*) > 20;"]', 0),
(3, 1, 'Tampilkan username dan asset_tag milik setiap pengguna.',
 '["SELECT u.username, a.asset_tag FROM users u JOIN assets a ON a.owner_user_id = u.user_id;","SELECT u.username, a.asset_tag FROM users u JOIN assets a ON a.asset_id = u.user_id;","SELECT username, asset_tag FROM users AND assets;","SELECT u.username, a.asset_tag FROM users u WHERE assets a ON a.owner_user_id = u.user_id;"]', 0),
(3, 2, 'Tampilkan username, waktu, dan status setiap login.',
 '["SELECT u.username, l.attempted_at, l.login_status FROM login_logs l JOIN users u ON u.user_id = l.user_id;","SELECT u.username, l.attempted_at, l.login_status FROM login_logs l JOIN users u ON u.user_id = l.login_id;","SELECT username, attempted_at, login_status FROM users WHERE login_logs;","SELECT u.username, l.attempted_at FROM users u GROUP BY login_logs l;"]', 0),
(3, 3, 'Tampilkan username dan aktivitas database dari login yang berasal dari 203.0.113.77.',
 '["SELECT u.username, d.executed_at, d.target_table FROM database_activity d JOIN login_logs l ON l.login_id = d.login_id JOIN users u ON u.user_id = d.user_id WHERE l.source_ip = ''203.0.113.77'';","SELECT u.username, d.executed_at, d.target_table FROM database_activity d JOIN login_logs l ON l.user_id = d.activity_id JOIN users u ON u.user_id = l.login_id;","SELECT username, target_table FROM users, database_activity WHERE source_ip = ''203.0.113.77'';","SELECT u.username, d.target_table FROM users u JOIN database_activity d WHERE login_logs.source_ip = ''203.0.113.77'';"]', 0),
(3, 4, 'Tampilkan username dan traffic keluar lebih dari 10.000.000 byte.',
 '["SELECT u.username, n.destination_ip, n.bytes_sent FROM network_traffic n JOIN users u ON u.user_id = n.user_id WHERE n.bytes_sent > 10000000;","SELECT u.username, n.destination_ip FROM network_traffic n JOIN users u ON u.user_id = n.traffic_id WHERE n.bytes_sent > 10000000;","SELECT username, bytes_sent FROM users WHERE network_traffic > 10000000;","SELECT u.username, n.bytes_sent FROM users u JOIN network_traffic n GROUP BY n.bytes_sent > 10000000;"]', 0),
(3, 5, 'Tampilkan pembuat laporan, login terkait, dan alamat IP untuk laporan yang memiliki related_login_id.',
 '["SELECT u.username, r.report_type, l.attempted_at, l.source_ip FROM incident_reports r JOIN users u ON u.user_id = r.reported_by_user_id JOIN login_logs l ON l.login_id = r.related_login_id;","SELECT u.username, r.report_type, l.source_ip FROM incident_reports r JOIN users u ON u.user_id = r.report_id JOIN login_logs l ON l.user_id = u.user_id;","SELECT username, report_type, source_ip FROM users JOIN incident_reports JOIN login_logs;","SELECT u.username, r.report_type FROM users u JOIN incident_reports r ON r.related_login_id = u.user_id JOIN login_logs l ON l.login_id = r.report_id;"]', 0)
on conflict (phase, order_num) do update set
  prompt = excluded.prompt,
  options = excluded.options,
  correct_index = excluded.correct_index;

insert into public.sql_case_audit_procedures (order_num, title, instruction, expected_columns) values
(1, 'Profil traffic harian', 'Ringkas jumlah event, rata-rata bytes_sent, dan total bytes_sent per tanggal. Identifikasi hari yang tidak mengikuti pola umum.', array['activity_date','traffic_events','avg_bytes_sent','total_bytes_sent']),
(2, 'Rush hour dan anomali per jam', 'Kelompokkan traffic berdasarkan jam. Bandingkan jam dengan event terbanyak terhadap jam dengan volume atau rata-rata byte terbesar.', array['activity_hour','traffic_events','avg_bytes_sent','total_bytes_sent']),
(3, 'Pola autentikasi harian', 'Hitung login event per tanggal dan login_status. Tentukan tanggal dengan kenaikan kegagalan login.', array['activity_date','login_status','login_events']),
(4, 'Pengguna dan aset Finance', 'Gunakan JOIN untuk menampilkan pengguna Finance serta aset yang terdaftar atas namanya.', array['username','full_name','asset_tag','hostname']),
(5, 'Sumber kegagalan login', 'Cari IP eksternal dengan sedikitnya lima login gagal dan hitung jumlah akun berbeda yang ditargetkan.', array['source_ip','country_code','failed_attempts','targeted_users']),
(6, 'Login di luar jam kerja', 'Hubungkan login_logs dan users untuk mencari login berhasil sebelum work_start atau setelah work_end.', array['login_id','username','attempted_at','source_ip','country_code']),
(7, 'Login tanpa aset terdaftar', 'Cari login berhasil dengan asset_id NULL dan tampilkan identitas penggunanya.', array['login_id','username','attempted_at','source_ip']),
(8, 'Aktivitas database sesi mencurigakan', 'Hubungkan database_activity, login_logs, dan users untuk menelusuri query dari IP yang paling perlu diselidiki.', array['username','executed_at','database_name','target_table','returned_rows','exported']),
(9, 'Ringkasan ekspor data', 'Hitung jumlah ekspor dan total returned_rows untuk setiap pengguna. Jangan langsung menyimpulkan ekspor terbesar sebagai serangan.', array['username','export_events','total_rows']),
(10, 'Transfer keluar berukuran besar', 'Cari transfer di atas 10.000.000 byte menuju alamat non-internal dan hubungkan dengan pengguna.', array['username','captured_at','destination_ip','bytes_sent']),
(11, 'Telaah laporan insiden', 'Hubungkan laporan dengan pembuatnya, baca description dan resolution_notes, lalu bedakan insiden, aktivitas resmi, dan petunjuk historis.', array['report_id','opened_at','username','report_type','severity','report_status'])
on conflict (order_num) do update set
  title = excluded.title,
  instruction = excluded.instruction,
  expected_columns = excluded.expected_columns;
